### ISSUE TITLE
Question around performance

### ISSUE THREAD

**Issue by sergioloom** [jo3-l/obscenity#22]
I'm considering using the library for processing a lot of text so I'm wondering if performance is something that has been considered in the library code and testing? It would be interesting to add some information about performance in the readme.

**Comment by jo3-l** [comment]
Sorry, I don't have any concrete benchmarks that I can share. That said, given how the library works, I would expect performance to be neither spectacular nor horrible — at its core, it is essentially a wrapper around sets of regular expressions. (When I last worked on this in 2021, I surveyed a number of similar libraries and found most to take a similar approach.)

Depending on the specifics of your use-case, faster string matching routines avoiding the overhead of regular expressions could be applicable. If you have no need for wildcards,

**Comment by jo3-l** [comment]
I'm going to close this off for now, but feel free to reopen if you have further questions.
