### ISSUE TITLE
Incorrect docs for skipNonAlphabeticTransformer

### ISSUE THREAD

**Issue by jwoertink** [jo3-l/obscenity#33]
https://github.com/jo3-l/obscenity/blob/79cfa630c964be79d1dc16eb0e5d65af4d68e7ab/src/transformer/skip-non-alphabetic/index.ts#L17-L19

It looks like this may have just been a copy/paste error. I think the docs are meant to mention `skipNonAlphabeticTransformer()` here instead :smile:

**Comment by jo3-l** [comment]
Thanks, fixed in dev branch via https://github.com/jo3-l/obscenity/commit/563159b76a7e2203ee6311af0dd505e96740009c.
