### ISSUE TITLE
Fix Typescript Types when using NodeNext module resolution

### ISSUE THREAD

**Issue by cevr** [jo3-l/obscenity#44]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `obscenity@0.1.4` for the project I'm working on.

Using `NodeNext` as the typescript `moduleResolution` causes the types to be unresolved.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/obscenity/package.json b/node_modules/obscenity/package.json
index 899188c..580449a 100644
--- a/node_modules/obscenity/package.json
+++ b/node_modules/obscenity/package.json
@@ -6,8 +6,14 @@
   "module": "./dist/index.mjs",
   "types": "./dist/index.d.ts",
   "exports": {
-    "import": "./dist/index.mjs",
-    "require": "./dist/index.js"
+    "import": {
+      "types": "./dist/index.d.ts",
+      "default":"./dist/index.mjs"
+    },
+    "require": {
+      "types": "./dist/index.d.ts",
+      "default": "./dist/index.js"
+    }
   },
   "repository": {
     "type": "git",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jo3-l** [comment]
Thanks for the report; I applied your patch verbatim and it should be available in the newest version of Obscenity. Apologies for the long turnaround.
