### ISSUE TITLE
bug: Censoring of the n-word results in more asterisks than expected

### ISSUE THREAD

**Issue by HatScripts** [jo3-l/obscenity#48]
### Expected behavior

-

### Actual behavior

`matcher.getAllMatches('nigger')` results in an array of length `2`, when it should only be `1`. This causes the resulting censored string to be `n*********r`, when it should be `n****r`.

<img width="300" alt="Screenshot 2024-01-05 171832" src="https://github.com/jo3-l/obscenity/assets/5691865/986dbbf1-4332-4440-9a0e-60b9e6814bcc">

### Minimal reproducible example

```typescript
import {
  RegExpMatcher,
  TextCensor,
  englishDataset,
  englishRecommendedTransformers,
  keepStartCensorStrategy,
  keepEndCensorStrategy,
  asteriskCensorStrategy
} from 'obscenity'

const matcher = new RegExpMatcher({
  ...englishDataset.build(),
  ...englishRecommendedTransformers
})

const strategy = keepStartCensorStrategy(keepEndCensorStrategy(asteriskCensorStrategy()))
const censor = new TextCensor().setStrategy(strategy)

const input = 'nigger'

const matches = matcher.getAllMatches(input)
console.log(matches)
console.log(censor.applyTo(input, matches))
```

### Steps to reproduce

1. Run above code
2. View console

### Node.js version

N/A

### Obscenity version

v0.1.4

### Priority

- [ ] Low
- [X] Medium
- [ ] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by jo3-l** [comment]
This should be fixed in the newest release of Obscenity; please let me know if it persists for you.

**Comment by HatScripts** [comment]
It's working as expected now. Thank you!
