### ISSUE TITLE
Package obscenity has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by Gabotron-ES** [jo3-l/obscenity#64]
### Expected behavior

I installed this package via npm to use in my react native 0.68.5 app

### Actual behavior

I get this error on my react native app: 

Package obscenity has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/gabriel/Desktop/proyectos/MyApp/node_modules/obscenity/package.json

### Minimal reproducible example

```typescript
npm install obscenity
```

### Steps to reproduce

npm install obscenity

### Additional context

My react native version:

"react-native": "0.68.5",

### Node.js version

16.0.0

### Obscenity version

0.2.0

### Priority

- [ ] Low
- [ ] Medium
- [X] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by jo3-l** [comment]
Thanks for the report. I am not familiar with React Native, so an minimal project that I could clone would be very useful in tracking down this issue. (As far as I can see, in a new project that does not use React Native, the import works correctly so your current reproduction steps are not sufficient.)

**Comment by jo3-l** [comment]
Per my above comment:
> As far as I can see, in a new project that does not use React Native, the import works correctly so your current reproduction steps are not sufficient.
I do not believe this issue represents a bug in Obscenity; it is more likely a configuration issue. That said, if you are willing to provide more details, please do feel free to reopen and I would happy to help investigate further.
