### ISSUE TITLE
Request: support accented letters in patterns

### ISSUE THREAD

**Issue by verekia** [jo3-l/obscenity#80]
### Description

```js
.addPhrase(phrase => phrase.setMetadata({ originalWord: 'coño' }).addPattern(pattern`coño`))
.addPhrase(phrase => phrase.setMetadata({ originalWord: 'pédé' }).addPattern(pattern`pédé`))
```
causes:
```
ParserError: 1:4: Cannot escape character 'u'; the only characters that can be escaped are the following: '\', '[', ']', '?', '|'.
```

### Solution

Add support for accented characters.

According to the suggestions of my Mac keyboard long-presses:

w: ŵ
e: èéêëěẽēėę
r: ř
t: țťþ
y: ýŷÿ
u: ùúûüǔũūűůu
i: ìíîïǐĩīıį
o: òóôöǒœøõō
a: àáâäǎæãåā
s: ßşșśš
d: ďð
g: ğġ
h: ħ
k: ķ
l: łļľ
z: źžż
c: çćčċ
n: ñńņň

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jo3-l** [comment]
I cannot reproduce the described error.
```javascript
const dataset = new DataSet()
	.addPhrase((phrase) => phrase.setMetadata({ originalWord: 'coño' }).addPattern(pattern`coño`))
	.addPhrase((phrase) => phrase.setMetadata({ originalWord: 'pédé' }).addPattern(pattern`pédé`));
console.log(new RegExpMatcher(dataset.build()).hasMatch('coño'));
```
prints `true` for me, as expected.

**Comment by jo3-l** [comment]
I'm going to close this off for now given the lack of response--my understanding is that this should already work. Please feel free to reopen the issue if you have a MRE showing otherwise. Thanks!
