### ISSUE TITLE
bug: grawlixCensorStrategy sometimes generates "@$$"

### ISSUE THREAD

**Issue by eltoder** [jo3-l/obscenity#82]
### Expected behavior

Censoring strategy should generate a replacement string that itself does not contain any profanity. However, since grawlixCensorStrategy returns a string of random characters that include "@" and "$", sometimes it generates "@$$", which is considered profanity by the default englishDataset/englishRecommendedTransformers matcher recommended in the guide.

### Actual behavior

This causes TextCensor with the default settings to sometimes replace "ass" or "@$$" with "@$$".

### Minimal reproducible example

```typescript
const {
	RegExpMatcher,
	TextCensor,
	englishDataset,
	englishRecommendedTransformers,
} = require('obscenity');

const matcher = new RegExpMatcher({
	...englishDataset.build(),
	...englishRecommendedTransformers,
});

const censor = new TextCensor();
const input = '@$$';
const matches = matcher.getAllMatches(input);
for (let i = 0; i < 100; i++) {
    if (censor.applyTo(input, matches) === input)
        console.log("input did not change after censoring");
}
```

### Node.js version

v20

### Obscenity version

v0.4.0

### Priority

- [ ] Low
- [X] Medium
- [ ] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by jo3-l** [comment]
Interesting find (and a mildly unfortunate issue)! A PR to generate another random string (in a loop as needed) if `@$$` was output originally is welcome. I can't guarantee a release within the next month, so if you need an immediate fix, you can switch to one of the other censor strategies provided, which do not suffer from this problem.
