### ISSUE TITLE
bug: pattern for "dick" has many false positives

### ISSUE THREAD

**Issue by eltoder** [jo3-l/obscenity#86]
### Expected behavior

It applies to many innocent words like "duck", "dock", "deck", etc.

### Actual behavior

```js
    .setMetadata({ originalWord: 'dick' })
    .addPattern((0, Pattern_1.pattern) `d?ck|`)
    .addPattern((0, Pattern_1.pattern) `d?cke[e]s|`)
    .addPattern((0, Pattern_1.pattern) `d?cks|`)
```

I think this matches all of the above, even though it should not.

### Node.js version

v20

### Obscenity version

v0.4.0

### Priority

- [ ] Low
- [ ] Medium
- [X] High

### Terms

- [X] I agree to follow the project's Code of Conduct.
- [X] I have searched existing issues for similar reports.

**Comment by jo3-l** [comment]
I'll get a patch release in today with the above fix. Thanks.

**Comment by eltoder** [comment]
Thanks! I made exactly the same change locally, so no need to rush.
